---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.22.6
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      # CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-gpt4all'
      ENABLE_MODULES: 'text2vec-gpt4all'
      CLUSTER_HOSTNAME: 'node1'
      GPT4ALL_INFERENCE_API: 'http://text2vec-gpt4all:8080'

  text2vec-gpt4all:
    image: semitechnologies/gpt4all-inference:all-MiniLM-L6-v2

      # sentence-transformers/all-MiniLM-L6-v2

  # contextionary:
  #   environment:
  #     OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
  #     EXTENSIONS_STORAGE_MODE: weaviate
  #     EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
  #     NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
  #     ENABLE_COMPOUND_SPLITTING: 'false'
  #   image: semitechnologies/contextionary:en0.16.0-v1.2.1
  #   ports:
  #   - 9999:9999
...
